-- Seed for the Postgres smoke test. Runs once, on first container start.
--
-- The smoke test is schema-agnostic: it introspects, picks a table with a
-- single-column primary key plus a scalar column, and probes a real value out
-- of it. This schema is shaped to give it something to find, and to make the
-- run exercise more than the happy path.
--
-- `smoke_order_lines` sorts first and has a composite primary key, so the
-- picker has to reject a table before it accepts one. A seed where the first
-- table always qualifies would never run that branch.

CREATE TABLE smoke_order_lines (
  order_id  bigint      NOT NULL,
  line_no   integer     NOT NULL,
  sku       text        NOT NULL,
  quantity  integer     NOT NULL,
  PRIMARY KEY (order_id, line_no)
);

CREATE TABLE smoke_orders (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status       text        NOT NULL,
  amount       numeric(10,2) NOT NULL,
  is_priority  boolean     NOT NULL DEFAULT false,
  placed_at    timestamptz NOT NULL,
  attributes   jsonb       NOT NULL DEFAULT '{}'::jsonb
);

-- An index, so introspection reports one and `get_by_index` has a target.
CREATE INDEX smoke_orders_status_placed_at_idx ON smoke_orders (status, placed_at);

INSERT INTO smoke_orders (status, amount, is_priority, placed_at, attributes) VALUES
  ('shipped',   120.00, false, timestamptz '2026-01-05 09:00:00+00', '{"channel": "web",    "region": "east"}'),
  ('shipped',    75.50, true,  timestamptz '2026-01-06 11:30:00+00', '{"channel": "mobile", "region": "west"}'),
  ('pending',   240.25, false, timestamptz '2026-02-01 15:45:00+00', '{"channel": "web",    "region": "east"}'),
  ('cancelled',  10.00, false, timestamptz '2026-02-14 08:15:00+00', '{"channel": "phone",  "region": "north"}');

INSERT INTO smoke_order_lines (order_id, line_no, sku, quantity) VALUES
  (1, 1, 'SKU-001', 2),
  (1, 2, 'SKU-002', 1),
  (2, 1, 'SKU-003', 5);
