/**
 * `approve` over a pairwise-generated set of inputs.
 *
 * `approve` is the only way a document enters the corpus, and it is a five-state
 * machine crossed with four optional arguments -- 160 combinations. Its other
 * tests enumerate failure paths by hand, which says nothing about the
 * combinations nobody thought of. The cases here come from PICT
 * (`models/approve.pict`, regenerated by the command in that file's header) and
 * cover every pair of values in 13 runs.
 *
 * A generated suite cannot assert a per-row expected output without restating
 * the state machine, which would only test the restatement. It asserts the
 * property the state machine exists to hold instead:
 *
 *   a document reaches the corpus only if its draft was on disk, the workflow
 *   had recorded a review, the caller gave an explanation, and the caller
 *   repeated the identical call past the deliberation gate.
 *
 * Any combination that promotes without all four is the bug this is looking
 * for. The suite also holds the tool to answering rather than throwing, for
 * every combination including the incoherent ones.
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";
import { MarkdownReader } from "../services/markdown-reader.js";
import { DRAFT_DIR, DRAFT_PREFIX } from "../constants.js";
import { AddHandler } from "../tools/instruction/handlers/add.js";
import { ApproveHandler } from "../tools/instruction/handlers/approve.js";
import { draftWorkflowManager } from "../workflows/draft-workflow.js";
import { resetMutationGatesForTesting } from "../services/mutation-gate.js";
import type { InstructionContext, ReminderConfig } from "../types/index.js";

const CASES_FILE = path.join(import.meta.dirname, "models", "approve.cases.tsv");

const config: ReminderConfig = {
  remindMcp: false,
  remindOrganize: false,
  customReminders: [],
  topicForEveryTask: null,
  infoValidSeconds: 60,
};

const EXPLANATION = "This records what we agreed, and it belongs under this prefix.";

interface Case {
  state: "editing" | "self_review" | "user_reviewing" | "pending_approval" | "missing";
  draft: "present" | "absent";
  notes: "given" | "omitted";
  explanation: "given" | "omitted";
  force: "on" | "off";
  mode: "single" | "batch";
  attempts: "once" | "repeated";
}

/** The committed PICT output, read as rows rather than restated here. */
async function readCases(): Promise<Case[]> {
  const lines = (await fs.readFile(CASES_FILE, "utf-8")).trim().split("\n");
  const header = lines[0].split("\t");
  return lines.slice(1).map((line) => {
    const values = line.split("\t");
    return Object.fromEntries(header.map((h, i) => [h, values[i]])) as unknown as Case;
  });
}

let tempDir: string;
let docsDir: string;
let reader: MarkdownReader;
let context: InstructionContext;
let ids: string[];

const add = new AddHandler();
const approve = new ApproveHandler();

function uniqueId(base: string): string {
  const id = `${base}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  ids.push(id);
  return id;
}

/** Put the draft and its workflow entry into the state the case names. */
async function arrange(params: { id: string; testCase: Case }): Promise<void> {
  const { id, testCase } = params;

  await add.execute({
    rawParams: {
      action: "add",
      id,
      content: `# ${id}\n\nBody.\n`,
      description: `desc ${id}`,
      whenToUse: ["testing"],
    },
    context,
  });

  // `add` leaves the entry in self_review. Walk it to where the case wants it.
  if (testCase.state === "user_reviewing" || testCase.state === "pending_approval") {
    await draftWorkflowManager.trigger({
      id,
      triggerParams: { action: "review_complete", notes: "reviewed: one topic" },
    });
  }
  if (testCase.state === "pending_approval") {
    await draftWorkflowManager.trigger({
      id,
      triggerParams: { action: "confirm", confirmed: true },
    });
  }
  if (testCase.state === "editing") {
    // `delete` rather than `clear`: `clear` leaves the persisted entry behind
    // and `getStatus` would read the old state straight back off disk.
    await draftWorkflowManager.delete({ id });
    await draftWorkflowManager.trigger({
      id,
      triggerParams: { action: "submit", content: `# ${id}\n\nBody.\n` },
    });
    await draftWorkflowManager.delete({ id });
  }
  if (testCase.state === "missing") {
    await draftWorkflowManager.delete({ id });
  }

  if (testCase.draft === "absent") {
    await fs.rm(path.join(docsDir, DRAFT_DIR, `${id}.md`), { force: true });
    reader.invalidateCache();
  }
}

/** The arguments the case describes. */
function argumentsFor(params: { id: string; testCase: Case }): Record<string, unknown> {
  const { id, testCase } = params;
  return {
    action: "approve",
    ...(testCase.mode === "batch" ? { ids: id } : { id }),
    ...(testCase.notes === "given" && { notes: "reviewed: one topic, ready" }),
    ...(testCase.explanation === "given" && { explanation: EXPLANATION }),
    ...(testCase.force === "on" && { force: true }),
  };
}

beforeEach(async () => {
  ids = [];
  tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "approve-combinations-"));
  docsDir = path.join(tempDir, "docs");
  await fs.mkdir(path.join(docsDir, DRAFT_DIR), { recursive: true });
  reader = new MarkdownReader(docsDir);
  context = { reader, config };
  resetMutationGatesForTesting();
});

afterEach(async () => {
  resetMutationGatesForTesting();
  for (const id of ids) await draftWorkflowManager.delete({ id });
  await fs.rm(tempDir, { recursive: true, force: true });
});

describe("every pair of inputs to approve", () => {
  /** The four conditions that together are the only way into the corpus. */
  function shouldPromote(testCase: Case): boolean {
    return (
      testCase.draft === "present" &&
      testCase.explanation === "given" &&
      testCase.attempts === "repeated" &&
      (testCase.state === "user_reviewing" || testCase.state === "pending_approval")
    );
  }

  it("promotes exactly the combinations that met all four conditions", async () => {
    // Both directions at once. Anything promoted without the four is a hole in
    // the gate; anything refused despite them is a document stuck outside the
    // corpus with nothing left to do about it.
    const cases = await readCases();
    expect(cases.length).toBeGreaterThan(0);

    const promoted: Case[] = [];

    for (const testCase of cases) {
      const id = uniqueId("combo");
      await arrange({ id, testCase });
      const args = argumentsFor({ id, testCase });

      const runs = testCase.attempts === "repeated" ? 2 : 1;
      for (let run = 0; run < runs; run++) {
        const result = await approve.execute({ rawParams: args, context });

        // Whatever the combination, the tool answers rather than throwing.
        expect(Array.isArray(result.content), JSON.stringify(testCase)).toBe(true);
        expect(result.content.length, JSON.stringify(testCase)).toBeGreaterThan(0);
      }

      reader.invalidateCache();
      if (await reader.documentExists(id)) {
        promoted.push(testCase);
      }
    }

    const expected = cases.filter(shouldPromote);
    // Not vacuous: the generated set reaches the write path.
    expect(expected.length).toBeGreaterThan(0);
    expect(promoted.map((c) => JSON.stringify(c)).sort()).toEqual(
      expected.map((c) => JSON.stringify(c)).sort()
    );
  }, 120_000);

  it("leaves the draft where it was whenever it refuses", async () => {
    // The other half of the safety property: a refusal must not half-move a
    // draft. Either the document is in the corpus or the draft is still there.
    const cases = await readCases();

    for (const testCase of cases.filter((c) => c.draft === "present")) {
      const id = uniqueId("intact");
      await arrange({ id, testCase });
      const args = argumentsFor({ id, testCase });

      const runs = testCase.attempts === "repeated" ? 2 : 1;
      for (let run = 0; run < runs; run++) {
        await approve.execute({ rawParams: args, context });
      }

      reader.invalidateCache();
      const inCorpus = await reader.documentExists(id);
      const stillDraft = await reader.documentExists(DRAFT_PREFIX + id);
      expect(inCorpus || stillDraft, JSON.stringify(testCase)).toBe(true);
    }
  }, 120_000);
});
