/**
 * `createPostgresDataSource` — recommended public surface.
 *
 * Wraps `mcp-shared-db-sql`'s engine-agnostic `createSqlDataSource` with the
 * Postgres dialect and a `pg`-style `query` callback. Callers supply only:
 *   - a `PgQueryClient` (e.g. from `createPgClient(url)`),
 *   - the `tableMetadata` map auto-generated by `mcp-shared-db-codegen`.
 */
import type { DataSource } from "mcp-shared-db";
import type { RdbTableMetadataMap } from "mcp-shared-db-core";
import { createSqlDataSource, type QueryFn } from "mcp-shared-db-sql";
import type { PgQueryClient } from "./client.js";
import { postgresDialect } from "./dialect.js";

export interface CreatePostgresDataSourceParams {
  client: PgQueryClient;
  tableMetadata: RdbTableMetadataMap;
}

export function createPostgresDataSource(
  params: CreatePostgresDataSourceParams,
): DataSource {
  const query: QueryFn = async ({ sql, values }) => {
    // `queryMode: 'extended'` (pg >= 8.11) forces pg-node down the
    // Parse + Bind + Execute path regardless of `values.length`. PG's
    // Parse message accepts a single statement only, so multi-statement
    // input (`SELECT 1; SELECT 2`) is rejected **at the wire**, before
    // PG executes any of it. Without this flag, an empty `values` array
    // would silently fall back to simple protocol, where PG runs every
    // statement and only the post-hoc `Array.isArray(r)` tripwire below
    // would catch it — too late, the second statement has already run.
    const r = (await params.client.query({
      text: sql,
      values,
      queryMode: "extended",
    })) as
      | { rows: Record<string, unknown>[] }
      | { rows: Record<string, unknown>[] }[];
    // Tripwire — under `queryMode: 'extended'` this branch should be
    // unreachable. Kept as a clear-error fallback in case a future
    // refactor regresses (or a different driver wires up here without
    // the same guarantee).
    if (Array.isArray(r)) {
      throw new Error(
        `Multi-statement SQL is not supported (got ${r.length} result sets). Pass a single statement.`,
      );
    }
    return { rows: r.rows };
  };
  return createSqlDataSource({
    query,
    dialect: postgresDialect,
    tableMetadata: params.tableMetadata,
  });
}
