/**
 * `createMysqlDataSource` — recommended public surface.
 *
 * Wraps `mcp-shared-db-sql`'s engine-agnostic `createSqlDataSource` with the
 * MySQL dialect and a mysql2-style `query` callback. Callers supply only:
 *   - a `MysqlQueryClient` (e.g. from `createMysqlClient(url)`),
 *   - the `tableMetadata` map auto-generated by `mcp-shared-db-codegen`.
 *
 * Multi-statement defence: mysql2's connection-level `multipleStatements:
 * false` (set in `client.ts`) rejects `SELECT 1; SELECT 2` at the wire
 * before the server executes any of it. PG's per-query `queryMode:
 * 'extended'` analogue isn't needed here — mysql2's per-query API has no
 * "simple protocol" override once the connection option is set.
 */
import type { DataSource } from "mcp-shared-db";
import type { RdbTableMetadataMap } from "mcp-shared-db-core";
import { createSqlDataSource, type QueryFn } from "mcp-shared-db-sql";
import type { MysqlQueryClient } from "./client.js";
import { mysqlDialect } from "./dialect.js";

export interface CreateMysqlDataSourceParams {
  client: MysqlQueryClient;
  tableMetadata: RdbTableMetadataMap;
}

export function createMysqlDataSource(
  params: CreateMysqlDataSourceParams,
): DataSource {
  const query: QueryFn = async ({ sql, values }) => {
    const r = await params.client.query({ text: sql, values });
    return { rows: r.rows };
  };
  return createSqlDataSource({
    query,
    dialect: mysqlDialect,
    tableMetadata: params.tableMetadata,
  });
}
